namespace TodoApi.Models;

public class TaskItem
{
     public int Id { get; set; } // Auto-generated by DB
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public bool Completed { get; set; }
}
